Adding follow thread message to anonymous thread posts
AmericanAirlines/AskingForAFriend pull request #18
Opened 2021-05-13 16:48 UTC by dre8597

## Pre-Requisites
- [X] Yes, I updated [Authors.md](../Authors.md) **OR** this is not my first contribution
- [X] Yes, I included and/or modified tests to cover relevent code **OR** my change is non-technical
- [X] Yes, I wrote this code entirely myself **OR** I properly attributed these changes in [Third Party Notices](../THIRD-PARTY-NOTICES.txt)

## Description of Changes

Adding an ephemeral message to anonymous questions to notify the user on how to follow a message/thread

## Related Issues

Closes #5

2021-05-13 18:56 UTC, SpencerKaiser requested changes
Quick changes

2021-05-13 18:56 UTC, SpencerKaiser commented on src/slack/views/postQuestionAnonymouslySubmitted.ts
> +    await app.client.chat.postEphemeral({
Can refactor the other uses in this file with the new pattern for using `client` from the method args?

2021-05-13 18:56 UTC, SpencerKaiser commented on src/slack/views/postQuestionAnonymouslySubmitted.ts
> +      text: `Since you won't be notified when someone replies to this question, here are the steps to follow it:
```suggestion
      text: `:warning: You won't be notified automatically when someone replies to this question. To get notifications from replies, follow the thread:
```

2021-05-13 18:56 UTC, SpencerKaiser commented on src/slack/views/postQuestionAnonymouslySubmitted.ts
> +         or Unfollow thread to stop receiving notifications.`,
```suggestion
      :one: Hover over the message (mobile app: tap the message)
      :two: Click message options (three dots)
      :three: Select \`Follow thread\``,
```

2021-05-17 14:28 UTC, dre8597 commented
Closing in favor of [this new PR](https://github.com/AmericanAirlines/AskingForAFriend/compare/pr/dre8597/18?expand=1)

2021-05-17 14:28 UTC, closed without merging